version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas_network

  mongodb:
    image: mongo:4.4.24
    container_name: saas_ecommerce_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: saas_ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - saas_network

  redis:
    image: redis:7-alpine
    container_name: saas_ecommerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas_network

  # Uncomment to enable pgAdmin for PostgreSQL management
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: saas_ecommerce_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@saasecommerce.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - saas_network

networks:
  saas_network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
