groups:
- name: node_alerts
  rules:
  # Alertas para o nó
  - alert: HighNodeCPU
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 10m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "Alto uso de CPU no nó {{ $labels.instance }}"
      description: "A CPU do nó {{ $labels.instance }} está em {{ $value }}% de utilização por mais de 10 minutos."

  - alert: HighNodeMemory
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 10m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "Alto uso de memória no nó {{ $labels.instance }}"
      description: "A memória do nó {{ $labels.instance }} está em {{ $value }}% de utilização por mais de 10 minutos."

  - alert: LowNodeDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"} < 10
    for: 10m
    labels:
      severity: critical
      team: infrastructure
    annotations:
      summary: "Espaço em disco baixo no nó {{ $labels.instance }}"
      description: "O espaço em disco do nó {{ $labels.instance }} está abaixo de 10%."

- name: container_alerts
  rules:
  # Alertas para contêineres
  - alert: ContainerKilled
    expr: time() - container_last_seen > 60
    for: 1m
    labels:
      severity: critical
      team: app
    annotations:
      summary: "Contêiner {{ $labels.name }} não está em execução"
      description: "O contêiner {{ $labels.name }} não está em execução há mais de 1 minuto."

  - alert: ContainerRestarted
    expr: increase(kube_pod_container_status_restarts_total[1h]) > 0
    for: 0m
    labels:
      severity: warning
      team: app
    annotations:
      summary: "Contêiner {{ $labels.container }} reiniciado"
      description: "O contêiner {{ $labels.container }} no pod {{ $labels.pod }} foi reiniciado {{ $value }} vezes na última hora."

- name: service_alerts
  rules:
  # Alertas para serviços
  - alert: HighRequestLatency
    expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)) > 1
    for: 10m
    labels:
      severity: warning
      team: app
    annotations:
      summary: "Alta latência no serviço {{ $labels.service }}"
      description: "O serviço {{ $labels.service }} tem um p99 de latência de {{ $value }} segundos."

  - alert: HighErrorRate
    expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by(service) / sum(rate(http_requests_total[5m])) by(service) * 100 > 5
    for: 5m
    labels:
      severity: critical
      team: app
    annotations:
      summary: "Alta taxa de erros no serviço {{ $labels.service }}"
      description: "O serviço {{ $labels.service }} tem uma taxa de erro de {{ $value }}%."

- name: database_alerts
  rules:
  # Alertas para bancos de dados
  - alert: PostgresqlDown
    expr: pg_up == 0
    for: 1m
    labels:
      severity: critical
      team: database
    annotations:
      summary: "PostgreSQL está inacessível"
      description: "O servidor PostgreSQL não está respondendo."

  - alert: HighPostgresqlConnections
    expr: sum(pg_stat_activity_count{datname!~"template.*|postgres"}) by (datname) > (pg_settings_max_connections * 0.8)
    for: 5m
    labels:
      severity: warning
      team: database
    annotations:
      summary: "Alto número de conexões no PostgreSQL"
      description: "O banco de dados {{ $labels.datname }} está usando mais de 80% das conexões máximas."

  - alert: HighMongoDBConnections
    expr: mongodb_connections_current > mongodb_connections_available * 0.8
    for: 5m
    labels:
      severity: warning
      team: database
    annotations:
      summary: "Alto número de conexões no MongoDB"
      description: "O MongoDB está usando mais de 80% das conexões disponíveis."

- name: rabbitmq_alerts
  rules:
  # Alertas para RabbitMQ
  - alert: RabbitMQNodeDown
    expr: rabbitmq_running == 0
    for: 1m
    labels:
      severity: critical
      team: infrastructure
    annotations:
      summary: "Nó RabbitMQ inacessível"
      description: "O nó RabbitMQ não está respondendo."

  - alert: RabbitMQHighMemory
    expr: rabbitmq_process_used_memory / rabbitmq_resident_memory_limit * 100 > 80
    for: 10m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "Alto uso de memória no RabbitMQ"
      description: "O RabbitMQ está usando mais de 80% da memória alocada."
