apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: saas_ecommerce
    user: ${DB_USER:-postgres}
    secureJsonData:
      password: ${DB_PASSWORD:-postgres}
    jsonData:
      sslmode: 'disable'
    editable: true

  - name: MongoDB
    type: mongodb
    access: proxy
    url: mongodb://${MONGO_INITDB_ROOT_USERNAME:-mongodb}:${MONGO_INITDB_ROOT_PASSWORD:-mongodb}@mongodb:27017/admin
    jsonData:
      ssl: false
    editable: true
